In [ ]:
!sudo echo -ne '\n' | sudo add-apt-repository ppa:alessandro-strada/ppa >/dev/null 2>&1 # note: >/dev/null 2>&1 is used to supress printing
!sudo apt update >/dev/null 2>&1
!sudo apt install google-drive-ocamlfuse >/dev/null 2>&1
!google-drive-ocamlfuse
!sudo apt-get install w3m >/dev/null 2>&1 # to act as web browser 
!xdg-settings set default-web-browser w3m.desktop >/dev/null 2>&1 # to set default browser 
%cd /content
!mkdir gdrive
%cd gdrive
!mkdir "MyDrive"
!google-drive-ocamlfuse "/content/gdrive/MyDrive"

/usr/bin/xdg-open: 869: www-browser: not found
/usr/bin/xdg-open: 869: links2: not found
/usr/bin/xdg-open: 869: elinks: not found
/usr/bin/xdg-open: 869: links: not found
/usr/bin/xdg-open: 869: lynx: not found
/usr/bin/xdg-open: 869: w3m: not found
xdg-open: no method available for opening 'https://accounts.google.com/o/oauth2/auth?client_id=564921029129.apps.googleusercontent.com&redirect_uri=https%3A%2F%2Fgd-ocaml-auth.appspot.com%2Foauth2callback&scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive&response_type=code&access_type=offline&approval_prompt=force&state=JWZS8D5YQ3W8XGhWnKTWPsq02Zqn9Jtf0qe5DxFksEc'
/bin/sh: 1: firefox: not found
/bin/sh: 1: google-chrome: not found
/bin/sh: 1: chromium-browser: not found
/bin/sh: 1: open: not found
Cannot retrieve auth tokens.
Failure("Error opening URL:https://accounts.google.com/o/oauth2/auth?client_id=564921029129.apps.googleusercontent.com&redirect_uri=https%3A%2F%2Fgd-ocaml-auth.appspot.com%2Foauth2callback&scope=https%3A%2F%2Fwww.

In [ ]:
################################################################################
# INSTALL CONDA ON GOOGLE COLAB
################################################################################
! wget https://repo.anaconda.com/miniconda/Miniconda3-py37_4.8.2-Linux-x86_64.sh
! chmod +x Miniconda3-py37_4.8.2-Linux-x86_64.sh
! bash ./Miniconda3-py37_4.8.2-Linux-x86_64.sh -b -f -p /usr/local
import sys
sys.path.append('/usr/local/lib/python3.7/site-packages/')

--2023-04-14 03:19:02--  https://repo.anaconda.com/miniconda/Miniconda3-py37_4.8.2-Linux-x86_64.sh
Resolving repo.anaconda.com (repo.anaconda.com)... 104.16.131.3, 104.16.130.3, 2606:4700::6810:8203, ...
Connecting to repo.anaconda.com (repo.anaconda.com)|104.16.131.3|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 85055499 (81M) [application/x-sh]
Saving to: ‘Miniconda3-py37_4.8.2-Linux-x86_64.sh’

Miniconda3-py37_4.8 100%[===================>]  81.12M   155MB/s    in 0.5s    

2023-04-14 03:19:02 (155 MB/s) - ‘Miniconda3-py37_4.8.2-Linux-x86_64.sh’ saved [85055499/85055499]

PREFIX=/usr/local
Unpacking payload ...
Solving environment: | / done

## Package Plan ##

  environment location: /usr/local

  added / updated specs:
    - _libgcc_mutex==0.1=main
    - asn1crypto==1.3.0=py37_0
    - ca-certificates==2020.1.1=0
    - certifi==2019.11.28=py37_0
    - cffi==1.14.0=py37h2e261b9_0
    - chardet==3.0.4=py37_1003
    - conda-package-handling==1.6.0=py37h

In [ ]:
#!pip install torch==1.4.0 torchvision==0.5.0+cu101 -f https://download.pytorch.org/whl/torch_stable.html

In [ ]:
#!pip install torch==1.4.0 -f https://download.pytorch.org/whl/torch_stable.html!

In [ ]:
!pip install torch==1.4.0+cu100 torchvision==0.5.0+cu100 -f https://download.pytorch.org/whl/torch_stable.html

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Looking in links: https://download.pytorch.org/whl/torch_stable.html
     |████████████████████████████████| 723.9 MB 24 kB/s 
     |████████████████████████████████| 4.0 MB 853 kB/s 
     |████████████████████████████████| 3.3 MB 7.3 MB/s 
     |████████████████████████████████| 15.7 MB 58.8 MB/s 


In [ ]:
#HoughNet_ROOT='/content/gdrive/MyDrive/HoughNet'
#HoughNet_ROOT='/content/gHoughNet'
#!git clone https://github.com/nerminsamet/HoughNet $HoughNet_ROOT

In [ ]:
HoughNet_ROOT='/content/gdrive/MyDrive/HoughNet'

In [ ]:
#!conda install pytorch==1.4.0 torchvision cudatoolkit=10.1 -c pytorch

In [ ]:
import os
os.chdir('/content/gdrive/MyDrive/HoughNet')
#os.chdir('/content/gHoughNet')

In [ ]:
!pip install -r requirements.txt

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 61.8 MB 1.2 MB/s 
     |████████████████████████████████| 1.9 MB 41.3 MB/s 
     |████████████████████████████████| 3.5 MB 51.2 MB/s 
     |████████████████████████████████| 11.2 MB 61.3 MB/s 
     |████████████████████████████████| 38.1 MB 410 kB/s 
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
     |████████████████████████████████| 34.6 MB 120 kB/s 
     |████████████████████████████████| 247 kB 50.2 MB/s 
     |████████████████████████████████| 965 kB 56.5 MB/s 
     |████████████████████████████████| 1.1 MB 50.8 MB/s 
     |████████████████████████████████| 98 kB 8.5 MB/s 
     |████████████████████████████████| 48 kB 6.7 MB/s 
  Created wheel for progress: filename=progress-1.6-py3-none-any.whl size=9615 sha256=24f1b6e917c2ee99f22fcb30edf2f7d7ed7155e0d8fcc0bc666516

In [ ]:
#!pip install gevent --pre
#!pip install auto-py-to-exe

In [ ]:
#!python -m pip install 'git+https://github.com/facebookresearch/detectron2.git'

In [ ]:
#!pip uninstall torch

In [ ]:
#!conda install pytorch==1.4.0 torchvision cudatoolkit=10.1 -c pytorch

In [ ]:
#!conda uninstall torch

In [ ]:
#!python -m pip install detectron2 -f https://dl.fbaipublicfiles.com/detectron2/wheels/cu101/torch1.4/index.html

In [ ]:
#!conda install https://anaconda.org/conda-forge/detectron2/0.2.1/download/linux-64/detectron2-0.2.1-py37h3340039_0.tar.bz2

In [ ]:
#!pip uninstall detectrone2==0.2.1

In [ ]:
!python -m pip install detectron2==0.2.1 -f https://dl.fbaipublicfiles.com/detectron2/wheels/cu100/torch1.4/index.html

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Looking in links: https://dl.fbaipublicfiles.com/detectron2/wheels/cu100/torch1.4/index.html
     |████████████████████████████████| 6.7 MB 7.6 MB/s 
     |████████████████████████████████| 6.0 MB 16.7 MB/s 
     |████████████████████████████████| 840 kB 52.4 MB/s 
     |████████████████████████████████| 50 kB 7.4 MB/s 
     |████████████████████████████████| 596 kB 67.9 MB/s 
     |████████████████████████████████| 4.9 MB 27.5 MB/s 
     |████████████████████████████████| 93 kB 1.2 MB/s 
     |████████████████████████████████| 781 kB 52.9 MB/s 
     |████████████████████████████████| 5.0 MB 58.6 MB/s 
     |████████████████████████████████| 126 kB 57.0 MB/s 
     |████████████████████████████████| 233 kB 55.4 MB/s 
     |████████████████████████████████| 1.0 MB 43.5 MB/s 
     |████████████████████████████████| 178 kB 47.0 MB/s 
     |████████████████████████████████| 42 kB 1.0 MB/s 
   

In [ ]:
#os.chdir('/content/gdrive')

In [ ]:
#from _ext import background 

In [ ]:
%cd $HoughNet_ROOT/src/lib/models/networks/DCNv2
!sh ./make.sh

/content/gdrive/MyDrive/HoughNet/src/lib/models/networks/DCNv2
running build
running build_ext
running develop
running egg_info
writing DCNv2.egg-info/PKG-INFO
writing dependency_links to DCNv2.egg-info/dependency_links.txt
writing top-level names to DCNv2.egg-info/top_level.txt
reading manifest file 'DCNv2.egg-info/SOURCES.txt'
writing manifest file 'DCNv2.egg-info/SOURCES.txt'
running build_ext
copying build/lib.linux-x86_64-3.7/_ext.cpython-37m-x86_64-linux-gnu.so -> 
Creating /usr/local/lib/python3.7/site-packages/DCNv2.egg-link (link to .)
Adding DCNv2 0.1 to easy-install.pth file

Installed /content/gdrive/MyDrive/HoughNet/src/lib/models/networks/DCNv2
Processing dependencies for DCNv2==0.1
Finished processing dependencies for DCNv2==0.1


In [ ]:
%cd $HoughNet_ROOT/src/lib/external
!ls
!sh Makefile

/content/gdrive/MyDrive/HoughNet/src/lib/external
__init__.py  nms.c				  nms.pyx      setup.py
Makefile     nms.cpython-37m-x86_64-linux-gnu.so  __pycache__
Makefile: 1: all:: not found
Compiling nms.pyx because it depends on /usr/local/lib/python3.7/site-packages/Cython/Includes/cpython/ref.pxd.
[1/1] Cythonizing nms.pyx
/usr/local/lib/python3.7/site-packages/Cython/Compiler/Main.py:369: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: /content/gdrive/MyDrive/HoughNet/src/lib/external/nms.pyx
  tree = Parsing.p_module(s, pxd, full_module_name)
running build_ext
building 'nms' extension
creating build
creating build/temp.linux-x86_64-3.7
gcc -pthread -B /usr/local/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/usr/local/lib/python3.7/site-packages/numpy/core/include -I/usr/local/include/python3.7m -c nms.c -o build/temp.linux-x86_64-3.7/nms.o -Wno-cpp -

In [ ]:
import torch
torch.cuda.is_available()

True

In [ ]:
import os
os.chdir('/content/gdrive/MyDrive/HoughNet')
#os.chdir('/content/gHoughNet')

In [ ]:
COCO_PATH='/content/gdrive/MyDrive/SyNet_COCO/SyNet/tensorpack/examples/FasterRCNN/coco_format'

In [ ]:
!python src/main.py ctdet --houghnet --exp_id coco_resdcn_101 --arch resdcn_101 --batch_size 2 --master_batch 2 --lr 1.75e-4 --gpus 1 --num_iters 10 --num_workers 16 --coco_path '/content/gdrive/MyDrive/SyNet_COCO/SyNet/tensorpack/examples/FasterRCNN/coco_format'

Fix size testing.
training chunk_sizes: [2]
The output will be saved to  /content/gdrive/MyDrive/HoughNet/src/lib/../../exp/ctdet/coco_resdcn_101
heads {'hm': 720, 'wh': 2, 'voting_heads': {'hm'}, 'reg': 2}
Namespace(K=100, arch='resdcn_101', aug_ddd=0.5, aug_rot=0, batch_size=2, cat_spec_wh=False, chunk_sizes=[2], coco_dir='', coco_path='/content/gdrive/MyDrive/SyNet_COCO/SyNet/tensorpack/examples/FasterRCNN/coco_format', data_dir='/content/gdrive/MyDrive/SyNet_COCO/SyNet/tensorpack/examples/FasterRCNN/coco_format', dataset='coco', debug=0, debug_dir='/content/gdrive/MyDrive/HoughNet/src/lib/../../exp/ctdet/coco_resdcn_101/debug', debugger_theme='white', demo='', dense_hp=False, dense_wh=False, dep_weight=1, dim_weight=1, down_ratio=4, eval_oracle_dep=False, eval_oracle_hm=False, eval_oracle_hmhp=False, eval_oracle_hp_offset=False, eval_oracle_kps=False, eval_oracle_offset=False, eval_oracle_wh=False, exp_dir='/content/gdrive/MyDrive/HoughNet/src/lib/../../exp/ctdet', exp_id='coco_res

In [ ]:
#!pip install torch -f https://download.pytorch.org/whl/cu101/torch-1.4.0-cp37-cp37m-linux_x86_64.whl

In [ ]:
#!python

In [ ]:
#from skimage.io import imread

In [ ]:
#!ls /content/gdrive

'My Drive'   MyDrive


In [ ]:
#!pip uninstall pytorch

In [ ]:
import torch

In [ ]:
print(torch.__version__)

1.13.1+cu116


In [ ]:
import os
os.chdir('/content/gdrive/MyDrive/HoughNet')
#os.chdir('/content/gHoughNet')

In [ ]:
!python src/test.py ctdet --houghnet --exp_id coco_resdcn_101 --batch_size 2 --arch resdcn_101 --keep_res  --load_model '/content/gdrive/MyDrive/HoughNet/exp/ctdet1/coco_resdcn_101/model_last.pth' --coco_path '/content/gdrive/MyDrive/QueryDet-PyTorch/data/visdrone/coco_format/'

Keep resolution testing.
training chunk_sizes: [2]
The output will be saved to  /content/gdrive/MyDrive/HoughNet/src/lib/../../exp/ctdet/coco_resdcn_101
heads {'hm': 108, 'wh': 2, 'voting_heads': {'hm'}, 'reg': 2}
Namespace(K=100, arch='resdcn_101', aug_ddd=0.5, aug_rot=0, batch_size=2, cat_spec_wh=False, chunk_sizes=[2], coco_dir='', coco_path='/content/gdrive/MyDrive/QueryDet-PyTorch/data/visdrone/coco_format/', data_dir='/content/gdrive/MyDrive/QueryDet-PyTorch/data/visdrone/coco_format/', dataset='coco', debug=0, debug_dir='/content/gdrive/MyDrive/HoughNet/src/lib/../../exp/ctdet/coco_resdcn_101/debug', debugger_theme='white', demo='', dense_hp=False, dense_wh=False, dep_weight=1, dim_weight=1, down_ratio=4, eval_oracle_dep=False, eval_oracle_hm=False, eval_oracle_hmhp=False, eval_oracle_hp_offset=False, eval_oracle_kps=False, eval_oracle_offset=False, eval_oracle_wh=False, exp_dir='/content/gdrive/MyDrive/HoughNet/src/lib/../../exp/ctdet', exp_id='coco_resdcn_101', fix_res=False, 

In [ ]:
!python src/demo.py ctdet --demo '/content/gdrive/MyDrive/9999937_00000_d_0000002.jpg' --vis_thresh 0.05 --keep_res --load_model '/content/gdrive/MyDrive/HoughNet/exp/ctdet1/coco_resdcn_101/model_last.pth' --debug 1 --resume

Keep resolution testing.
training chunk_sizes: [1]
The output will be saved to  /content/gdrive/MyDrive/HoughNet/
heads {'hm': 12, 'wh': 2, 'voting_heads': {}, 'reg': 2}
Creating model...
=> loading pretrained model https://download.pytorch.org/models/resnet101-5d3b4d8f.pth
=> init deconv weights from normal distribution
loaded /content/gdrive/MyDrive/HoughNet/exp/ctdet1/coco_resdcn_101/model_last.pth, epoch 139
Drop parameter voting_hm.deconv_filters.0.weight.
Skip loading parameter hm.2.weight, required shapetorch.Size([12, 64, 1, 1]), loaded shapetorch.Size([108, 64, 1, 1]).
Skip loading parameter hm.2.bias, required shapetorch.Size([12]), loaded shapetorch.Size([108]).
['/content/gdrive/MyDrive/9999937_00000_d_0000002.jpg']
aviyo
True
lo
[[[103 120  83]
  [ 56  74  37]
  [ 70  91  53]
  ...
  [ 32  42  25]
  [ 33  44  24]
  [ 35  46  26]]

 [[ 90 107  73]
  [ 82 103  65]
  [ 76  99  61]
  ...
  [ 30  40  23]
  [ 31  41  24]
  [ 31  42  22]]

 [[ 46  70  36]
  [ 72  98  62]
  [ 65  

In [ ]:
import os
os.chdir('/content')

In [ ]:
CenterNet_ROOT='/content/CenterNet'
!git clone https://github.com/xingyizhou/CenterNet $CenterNet_ROOT

Cloning into '/content/CenterNet'...
remote: Enumerating objects: 397, done.
remote: Total 397 (delta 0), reused 0 (delta 0), pack-reused 397
Receiving objects: 100% (397/397), 6.26 MiB | 14.95 MiB/s, done.
Resolving deltas: 100% (179/179), done.


In [ ]:
os.chdir(CenterNet_ROOT)

In [ ]:
!pip install -r requirements.txt

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 61.8 MB 1.2 MB/s 
     |████████████████████████████████| 1.9 MB 50.0 MB/s 
     |████████████████████████████████| 3.5 MB 63.9 MB/s 
     |████████████████████████████████| 11.2 MB 64.0 MB/s 
     |████████████████████████████████| 38.1 MB 1.3 MB/s 
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
     |████████████████████████████████| 15.7 MB 60.6 MB/s 
     |████████████████████████████████| 34.6 MB 139 kB/s 
     |████████████████████████████████| 98 kB 9.6 MB/s 
     |████████████████████████████████| 965 kB 56.1 MB/s 
     |████████████████████████████████| 48 kB 6.6 MB/s 
     |████████████████████████████████| 3.3 MB 48.9 MB/s 
     |████████████████████████████████| 1.1 MB 38.3 MB/s 
     |████████████████████████████████| 247 kB 46.9 MB/s 
  Created wheel for pro

In [ ]:
%cd $CenterNet_ROOT/src/lib/models/networks/DCNv2
!sh ./make.sh

/content/CenterNet/src/lib/models/networks/DCNv2
/content/CenterNet/src/lib/models/networks/DCNv2
Traceback (most recent call last):
  File "build.py", line 3, in <module>
    from torch.utils.ffi import create_extension
  File "/usr/local/lib/python3.7/site-packages/torch/utils/ffi/__init__.py", line 1, in <module>
    raise ImportError("torch.utils.ffi is deprecated. Please use cpp extensions instead.")
ImportError: torch.utils.ffi is deprecated. Please use cpp extensions instead.
Traceback (most recent call last):
  File "build_double.py", line 3, in <module>
    from torch.utils.ffi import create_extension
  File "/usr/local/lib/python3.7/site-packages/torch/utils/ffi/__init__.py", line 1, in <module>
    raise ImportError("torch.utils.ffi is deprecated. Please use cpp extensions instead.")
ImportError: torch.utils.ffi is deprecated. Please use cpp extensions instead.


In [ ]:
!conda install -c anaconda ipykernel

Solving environment: / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / done


==> WARNING: A newer version of conda exists. <==
  current version: 4.8.2
  latest version: 23.3.1

Please update conda by running

    $ conda update -n base -c defaults conda



## Package Plan ##

  environment location: /usr/local

  added / updated specs:
    - ipykernel


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    _openmp_mutex-5.1          |            1_gnu          20 KB  anaconda
    backcall-0.2.0             |     pyhd3eb1b0_0          13 KB  anaconda
    ca-certificates-2023.01.10 |       h06a4308_0         127 KB  anaconda
    certifi-2022.12.7          |   py37h06a4308_0         152 KB  anaconda
    conda-23.1.0               |   py37h06a4308_0         955 KB  anaconda
    debugpy-1.5.1              |   py37h2